version: '3.4'
services:
  golang:
    image: flemay/golang:1-stretch
    env_file: .env
    volumes:
      - .:/go/src/{{cookiecutter.app_go_package_path}}
    working_dir: /go/src/{{cookiecutter.app_go_package_path}}

  serverless:
    image: flemay/serverless
    env_file: .env
    volumes:
      - ~/.aws:/root/.aws
      - .:/opt/app
    working_dir: /opt/app

